apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicure-deployment
  labels:
    app: medicure-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: medicure-app
  template:
    metadata:
      labels:
        app: medicure-app
    spec:
      containers:
      - name: medicure-container
        image: bvky/medicure-image:v1.0
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: medicure-service
  labels:
    app: medicure-app
spec:
  selector:
    app: medicure-app

  type: NodePort
  ports:
  - nodePort: 31010  
    port: 8082
    targetPort: 8082
